#test freezewindow with disabled
shared:
  image: node:6
jobs:
  blah:
    steps:
      - echo: echo hi
    requires: [~pr, ~commit]
  test:
    steps:
      - time: node time.js
   freezeWindows: ['* 20-21 ? * *']
    requires: [blah]
